name: seis2rock
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.8.5
  - pip
  - numpy==1.23.3  #1.19.2
  - scipy==1.5.2
  - matplotlib==3.4.2
  - jupyter==1.0.0
  - pip:
    - pylops==2.1.0
    - pyproximal==0.6.0
    - segyio==1.9.6
    - pandas==1.4.1
    # - git+https://github.com/DIG-Kaust/pysubsurface
    - numba
    - pyvista
    - lasio
    - segyio
    - seaborn
    - matplotlib-scalebar
    - tqdm
    
